package de.onenightcar.domain.controller;

import de.onenightcar.domain.model.person.PaymentMethod;
import de.onenightcar.domain.storage.packageRepositories.personRepository.PaymentMethodRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;


@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired      // This means to get the bean called paymentMethodRepository
                    // Which is auto-generated by Spring, we will use it to handle the data
    private PaymentMethodRepository paymentMethodRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewPaymentMethod (@RequestParam String cardNumber, @RequestParam String ccv) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        PaymentMethod pm = new PaymentMethod();
        pm.setCardNumber(cardNumber);
        pm.setCCV(ccv);
        paymentMethodRepository.save(pm);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<PaymentMethod> getAllPaymentMethods() {
        // This returns a JSON or XML with the users
        return paymentMethodRepository.findAll();
    }
}
